"""
Generated by gazelle. DO NOT EDIT.
This file contains Go dependency declarations for Bazel.
To update: bazel run //:gazelle-update-repos
"""

def go_dependencies():
    """Declare Go dependencies for Bazel."""
    pass
